# Generated by Django 5.0.6 on 2024-07-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=600)),
                ('price', models.IntegerField(default=0)),
                ('product_image', models.FileField(default=None, max_length=250, null=True, upload_to='product/')),
            ],
        ),
    ]
