# Generated by Django 5.0.6 on 2024-07-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='des',
            field=models.TextField(),
        ),
    ]
