# Generated by Django 5.0.6 on 2024-07-30 14:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='product_name', unique=True),
        ),
    ]
