# Generated by Django 5.0.6 on 2024-07-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_icon',
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='ourservices/'),
        ),
    ]
