# Generated by Django 5.0.6 on 2024-08-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
