# Generated by Django 5.0.6 on 2024-08-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
