# Generated by Django 5.0.6 on 2024-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.FileField(upload_to='product/'),
        ),
    ]
